import '@/scss/base.scss'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>
            <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width"/>
            <meta httpEquiv="Content-Type" content="text/html; charset=utf-8"/>
            <meta charSet="utf-8"/>
            <meta httpEquiv="content-language" content="fa"/>
            <meta name="language" content="fa"/>
            <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
            <link rel="apple-touch-icon" sizes="180x180" href="/img/ico/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/img/ico/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/img/ico/favicon-16x16.png"/>
            <link rel="manifest" href="/img/ico/site.webmanifest"/>
            <meta name="msapplication-TileColor" content="#8560FC"/>
            <meta name="theme-color" content="#ffffff"/>
            <link rel="preload" href="/fonts/iconmoon/custom.woff2" as="font" type="font/woff2"
                  crossOrigin="anonymous"/>
            <link rel="preload" href="/fonts/iransans/regular/IRANSansWebNum.woff2" as="font" type="font/woff2"
                  crossOrigin="anonymous"/>
            <base href="/"/>

        </head>
        <body>{children}</body>
        </html>
    )
}
